name: "Daily Fudan"

on:
  schedule:
    - cron: "0 22 * * *"  # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:

env:
  # auto merge from y1ndan/genshin-impact-helper, default: false
  ALLOW_MERGE: 'true'
  RUN_ENV: 'prod'
  TZ: 'Asia/Shanghai'

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master

      - name: Auto merge
        if: ${{ env.ALLOW_MERGE != 'false' }}
        run: |
          git config --global user.name  '21110850045'
          git config --global user.email '18210850006@fudan.edu.cn'
          git remote add upstream https://github.com/k652/daily_fudan
          git pull upstream master --allow-unrelated-histories
          git push origin master
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-300 -n 1)

      - name: Run sign
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 ./dailyFudan.py '${{ '21110850045 Zhao0914.'}}'
